"""Every version identifier that can change what the model produces (B-S13.4).

`rules/ml.md` requires a recorded dependency graph — model, prompt template,
taxonomy, thresholds — for any inference to be reproducible. These constants are
that graph. They are the cache key, they are stored on every prediction, and they
are what makes a re-run under new rules add history instead of overwriting it.

Bump the relevant constant whenever the thing it names changes. A prompt edited
without a version bump would serve cached output generated by the old wording,
which is the specific failure this file prevents.
"""

from __future__ import annotations

#: The label taxonomy in `amanah.domain.enums`: relevance, stance, hate types,
#: severity bands. Bumping it invalidates every cached classification.
TAXONOMY_VERSION = "taxonomy-1"

#: The normalization rules that produced the model's input text. Mirrors
#: `amanah.canonical.text.NORMALIZATION_VERSION` into the cache key, so text
#: renormalized under new rules is reclassified rather than served from cache.
INFERENCE_VERSION = "inference-1"

#: Threshold set mapping a numeric score onto a confidence tier. Provisional
#: until calibrated against a reviewed holdout (B-S14.4).
CONFIDENCE_THRESHOLD_VERSION = "thresholds-1-provisional"

#: Deterministic aggregation rules behind stored metric buckets. Part of a
#: bucket's identity, so recomputing under new rules adds a bucket rather than
#: rewriting the one a published figure already cited.
FILTER_VERSION = "filters-1"

#: The fact-bundle assembly rules. Part of an insight's cache key: a bundle built
#: under different rules is a different set of facts, even for the same filters.
FACT_BUNDLE_VERSION = "facts-1"
